### ISSUE TITLE
Cannot specify which Python virtualenv to use with the esp-idf toolchain

### ISSUE THREAD

**Issue by rambo** [paoloach/ESP32#1]
Best practice is to install everything in it's own virtualenv (instead of globally), as such we should have option of specifying path to the virtualenv we wish to activate for running Makefile commands.

**Comment by paoloach** [comment]
I'm not a python expert, so to better understand, you want a new input box where specify the virtualenv path and, if set, before to run the makefile, execute the command:
"virtualenv _virtualenv_path_"

right ?

**Comment by rambo** [comment]
It's enough to define `PYTHON=/path/to/virtualenv/bin/python` as environment veriable before executing makefile commands, I actually managed to do this in `cmake` settings in CLion itself after submitting this issue, but handier to have it in the same place as the other settings.

**Comment by paoloach** [comment]
Allow to select a file in the SDK tool configuration
